default.nova.mysql.user = "novadbadmin"
set_unless.nova.mysql.password = "novasecret"
default.nova.mysql.database = "nova"
set_unless.nova.mysql.host = "localhost"

default.nova.rabbitmq.user = "nova"
set_unless.nova.rabbitmq.password = "secure_password"
default.nova.rabbitmq.vhost = "/nova"

default.nova.cc_host = "127.0.0.1:9292"
default.nova.fixed_range = "192.168.0.0/16"
default.nova.glance_api_servers = "127.0.0.1:9292"
default.nova.iscsi_ip_prefix = "192.168."
default.nova.network_size = "8"
default.nova.nova_url = "http://127.0.0.1:8774/v1.1/"
default.nova.rabbitmq_host = "127.0.0.1"
default.nova.routing_source_ip = "127.0.0.1"
default.nova.s3_host = "127.0.0.1"
default.nova.sql_connection = "mysql://#{node.nova.mysql.user}" +
  ":#{node.nova.mysql.password}@#{node.nova.mysql.host}/#{node.nova.mysql.database}"
default.nova.vlan_interface = "br100"
default.nova.public_interface = "eth1"
