maintainer       "Tim Dysinger"
maintainer_email "tim@dysinger.net"
license          "Apache 2.0"
description      "Installs/Configures OpenStack Nova"
version          "0.1.0"
supports         "ubuntu"
depends          "mysql"
